"""export_resultant_golden.py: writes frontend/src/fixtures/resultant_golden.json (issue #10).

This file is the link between the two implementations of the resultant. The maths lives
twice, once in `src/sar/model/interpolate.py` for the engine and once in
`frontend/src/interpolate.js` for the browser, because the published site is static and
has no server to ask. Two implementations of the same formula drift apart silently, and a
map that is subtly wrong still looks entirely reasonable on screen.

So Python is the reference. This script runs it over a small grid and records both the
inputs and the answers. `frontend/tests/interpolate.test.js` reads the same file, feeds the
JavaScript the identical inputs, and asserts the answers match. If either side is edited
alone, that test fails and names the case.

PREFER REAL DATA. Given `--from`, the fixture is cut from a stored forcing file: a small
window of real HYCOM currents, land and all. That is worth more than invented numbers,
because it exercises the float32 coordinate axes and the NaN land mask the archive
actually has, and those are what the browser will meet. Without `--from` the grid is
synthetic, so the fixture can still be regenerated by someone with no archive.

Either way the grid stays a few cells across, the file stays a few kilobytes, and
longitude is written in the frontend's DISPLAY convention of -180 to 180, which is what
the manifest gives the browser.

Run:
    python scripts/export_resultant_golden.py \\
        --from data/current/current_2019-01-01_2019-01-03.txt
    python scripts/export_resultant_golden.py          # synthetic, needs no archive
"""

import argparse
import json
from pathlib import Path

import numpy as np

from sar.model.interpolate import (
    MissingCornerError,
    OutOfCoverageError,
    bilinear_weights,
    interpolation_uncertainty,
    resultant_vector,
    speed_direction,
    time_blend,
)

OUT = Path("frontend/src/fixtures/resultant_golden.json")

# The synthetic fallback grid, in the frontend's own terms: j indexes latitude and i
# indexes longitude, and longitude is already in display form.
GRID = {"lat0": 26.0, "dlat": 0.04, "nlat": 8, "lon0": -79.0, "dlon": 0.08, "nlon": 8}
FRAMES = 2

# Cells that are land in the synthetic grid, as (j, i). Kept away from the middle, where
# the ordinary cases sit, and reachable by the land failure case.
LAND = [(6, 1), (7, 1), (7, 2)]

# How many cells across to cut when the fixture comes from a real file. Big enough to hold
# every case with a clear margin, small enough to keep the fixture readable.
CUT = {"nlat": 8, "nlon": 8, "frames": 2}


def synthetic_field() -> np.ndarray:
    """A turning, non-linear field, so a wrong weight cannot pass by coincidence.

    Shape (frames, nlat, nlon, 2). Deliberately not linear: a linear field is reproduced
    exactly by any sane weighting, including several wrong ones.
    """
    j = np.arange(GRID["nlat"])[None, :, None]
    i = np.arange(GRID["nlon"])[None, None, :]
    f = np.arange(FRAMES)[:, None, None]
    u = 0.5 + 0.3 * np.sin(0.7 * i + 0.4 * j) + 0.1 * f
    v = -0.2 + 0.4 * np.cos(0.5 * i - 0.6 * j) - 0.05 * f
    field = np.stack([u, v], axis=-1)
    for jj, ii in LAND:
        field[:, jj, ii, :] = np.nan
    return field


def cut_from_archive(path: Path) -> tuple[dict, np.ndarray, list]:
    """Cut a small window out of a stored forcing file, with real land in it.

    Returns the grid in the frontend's terms, the field as (frames, nlat, nlon, 2), and
    the land cells found. The window is chosen to CONTAIN land rather than to avoid it:
    a coast is where the browser is most likely to meet a missing corner, and inventing
    a NaN would not prove that the two sides treat a real one alike.
    """
    from sar.utils.data_io import open_forcing
    from sar.utils.geo import regular_axis_step, to_display_longitude

    ds = open_forcing(path)
    u_name, v_name = ("water_u", "water_v") if "water_u" in ds else ("u10", "v10")
    land = np.isnan(ds[u_name].values[0])

    # Aim for about a quarter land: enough that the missing-corner case has somewhere to
    # stand, not so much that the ordinary cases have nowhere.
    best, best_score = None, -1.0
    for j in range(0, land.shape[0] - CUT["nlat"], 7):
        for i in range(0, land.shape[1] - CUT["nlon"], 7):
            share = float(land[j:j + CUT["nlat"], i:i + CUT["nlon"]].mean())
            score = -abs(share - 0.25)
            if 0.0 < share < 0.4 and score > best_score:
                best, best_score = (j, i), score
    if best is None:
        raise SystemExit(
            f"{path} holds no {CUT['nlat']} by {CUT['nlon']} window mixing land and sea; "
            "run without --from for the synthetic grid"
        )

    j0, i0 = best
    lat = ds.lat.values[j0:j0 + CUT["nlat"]]
    lon = to_display_longitude(ds.lon.values[i0:i0 + CUT["nlon"]])
    grid = {
        "lat0": float(lat[0]), "dlat": regular_axis_step(lat, "lat"), "nlat": int(lat.size),
        "lon0": float(lon[0]), "dlon": regular_axis_step(lon, "lon"), "nlon": int(lon.size),
    }

    window = np.stack(
        [
            ds[name].values[:CUT["frames"], j0:j0 + CUT["nlat"], i0:i0 + CUT["nlon"]]
            for name in (u_name, v_name)
        ],
        axis=-1,
    ).astype(float)
    land_cells = [[int(a), int(b)] for a, b in np.argwhere(np.isnan(window[0, :, :, 0]))]
    ds.close()
    return grid, window, land_cells


def sample(grid: dict, field: np.ndarray, frame: int, lat: float, lon: float) -> dict:
    """The resultant at one point of the fixture grid, by the same steps as the engine.

    This repeats the engine's index arithmetic rather than calling `sample_field`, because
    `sample_field` wants an xarray dataset in the stored 0 to 360 convention while the
    browser works on a plain array in display longitude. The arithmetic being checked is
    identical; only the container differs.
    """
    g = grid
    j = int(round((lat - g["lat0"]) / g["dlat"]))
    i = int(round((lon - g["lon0"]) / g["dlon"]))
    if not (0 <= j < g["nlat"] and 0 <= i < g["nlon"]):
        raise OutOfCoverageError(f"({lat}, {lon}) is outside the fixture grid")

    dy = lat - (g["lat0"] + j * g["dlat"])
    dx = lon - (g["lon0"] + i * g["dlon"])
    sy = 1 if dy >= 0 else -1
    sx = 1 if dx >= 0 else -1
    if not 0 <= j + sy < g["nlat"]:
        sy = -sy
    if not 0 <= i + sx < g["nlon"]:
        sx = -sx

    weights = bilinear_weights(abs(dy) / g["dlat"], abs(dx) / g["dlon"])
    cells = [(j, i), (j, i + sx), (j + sy, i), (j + sy, i + sx)]
    corners = np.array([field[frame, cj, ci] for cj, ci in cells], dtype=float)

    missing = np.isnan(corners).any(axis=1)
    if missing.any():
        n = int(missing.sum())
        raise MissingCornerError(f"{'all 4' if n == 4 else f'{n} of 4'} corners are land")

    u, v = resultant_vector(corners, weights)
    speed, bearing = speed_direction(u, v)
    return {
        "lat": lat,
        "lon": lon,
        "frame": frame,
        "cells": [list(c) for c in cells],
        "weights": weights.tolist(),
        "u": u,
        "v": v,
        "speed": speed,
        "direction_to_deg": bearing,
        "uncertainty": interpolation_uncertainty(corners, weights),
    }


def _at(grid: dict, j: float, i: float) -> tuple:
    """A position given in fractional cell indices, which keeps the cases grid-agnostic."""
    return (grid["lat0"] + j * grid["dlat"], grid["lon0"] + i * grid["dlon"])


def _sea_cell(field: np.ndarray, grid: dict) -> tuple:
    """A cell whose whole neighbourhood is sea, so the ordinary cases sit off any coast."""
    for j in range(1, grid["nlat"] - 2):
        for i in range(1, grid["nlon"] - 2):
            if np.isfinite(field[:, j - 1:j + 3, i - 1:i + 3, :]).all():
                return j, i
    raise SystemExit("the cut window has no open-sea neighbourhood; widen CUT")


def _land_point(field: np.ndarray, grid: dict):
    """A position whose four corners include land, or None if the window holds none."""
    for j in range(grid["nlat"] - 1):
        for i in range(grid["nlon"] - 1):
            if not np.isfinite(field[:, j:j + 2, i:i + 2, :]).all():
                return _at(grid, j + 0.3, i + 0.3)
    return None


def build(grid: dict, field: np.ndarray, land_cells: list, source: str) -> dict:
    frames = int(field.shape[0])
    sj, si = _sea_cell(field, grid)

    # Positions are given in fractional cell indices, so one set of cases works both on
    # the synthetic grid and on any window cut from the archive.
    points = {
        "interior": _at(grid, sj + 0.33, si + 0.41),
        "off centre": _at(grid, sj + 0.78, si + 0.12),
        "on a grid point": _at(grid, sj, si),
        "on a longitude line": _at(grid, sj + 0.33, si),
        "on a latitude line": _at(grid, sj, si + 0.41),
        "just inside a cell": _at(grid, sj + 0.01, si + 0.99),
    }

    cases = []
    for name, (lat, lon) in points.items():
        for frame in range(frames):
            case = sample(grid, field, frame, lat, lon)
            case["name"] = f"{name}, frame {frame}"
            cases.append(case)

    # The failure modes, recorded by the NAME of the error rather than its message, so the
    # wording can be improved on either side without breaking the other.
    wanted = [
        ("north of the grid", _at(grid, grid["nlat"] + 2, si), "OutOfCoverageError"),
        ("west of the grid", _at(grid, sj, -3), "OutOfCoverageError"),
    ]
    land_point = _land_point(field, grid)
    if land_point is not None:
        wanted.append(("a land corner", land_point, "MissingCornerError"))

    failures = []
    for name, (lat, lon), err in wanted:
        try:
            sample(grid, field, 0, lat, lon)
        except (OutOfCoverageError, MissingCornerError) as exc:
            assert type(exc).__name__ == err, f"{name} raised {type(exc).__name__}"
            failures.append({"name": name, "lat": lat, "lon": lon, "error": err})
        else:
            raise AssertionError(f"{name} was expected to raise {err} and did not")

    # Time blending, which the browser needs when a wind frame falls between two current
    # frames. Recorded here so the browser's version is checked against Python too.
    c1 = np.array([[0.4, -0.1], [0.9, 0.3], [-0.2, 0.5], [0.0, 0.0]])
    c2 = np.array([[0.6, 0.2], [0.1, -0.4], [0.3, 0.5], [1.0, -1.0]])
    blends = [
        {"frac": frac, "corners": time_blend(c1, c2, frac).tolist()}
        for frac in (0.0, 0.25, 0.5, 1.0)
    ]

    return {
        "generated_by": "scripts/export_resultant_golden.py",
        "reference": "src/sar/model/interpolate.py",
        "source": source,
        "note": (
            "Python is the reference implementation. frontend/tests/interpolate.test.js "
            "asserts the browser port reproduces every case here. Regenerate with: "
            "python scripts/export_resultant_golden.py --from <a stored forcing file>"
        ),
        "tolerance": 1e-9,
        "grid": grid,
        "frames": frames,
        "land_cells": land_cells,
        # Interleaved [frame][lat][lon][u, v], the layout BufferSource already expects.
        # NaN is not valid JSON, so land arrives as null and the test turns it back.
        "field": [None if np.isnan(x) else float(x) for x in field.ravel()],
        "cases": cases,
        "failures": failures,
        "time_blend": {"corners_t1": c1.tolist(), "corners_t2": c2.tolist(), "blends": blends},
    }


def main() -> None:
    p = argparse.ArgumentParser(description="Write the golden fixture for the browser port")
    p.add_argument("--out", default=str(OUT))
    p.add_argument("--from", dest="source",
                   help="a stored forcing file to cut the fixture from; omit for a "
                        "synthetic grid that needs no archive")
    args = p.parse_args()

    if args.source:
        grid, field, land_cells = cut_from_archive(Path(args.source))
        source = f"cut from {Path(args.source).name}"
    else:
        grid, field = GRID, synthetic_field()
        land_cells = [list(c) for c in LAND]
        source = "synthetic; no archive was used"

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = build(grid, field, land_cells, source)
    out.write_text(json.dumps(payload, indent=1), encoding="utf-8")

    print(
        f"wrote {out}\n"
        f"  {source}\n"
        f"  grid {grid['nlat']} by {grid['nlon']}, {payload['frames']} frames, "
        f"{len(land_cells)} land cells\n"
        f"  {len(payload['cases'])} cases, {len(payload['failures'])} failures"
    )


if __name__ == "__main__":
    main()
